### ISSUE TITLE
FileNotFoundError , LD-PGTA/MODELS/MODELS12.p

### ISSUE THREAD

**Issue by lituan** [mccoy-lab/LD-PGTA#2]
Hi

I tried this excellent tool following the manual, and got error during stage 4, I checked   ANEUPLOIDY_TEST.py,  found that line 380 will search three files, MODELS18.p  MODELS16.p  MODELS12.p, but these three files are not in this git repository, how can I get these three files?

**Comment by scikal** [comment]
Hi,

Thank you for your comment!

You can run MAKE_STATISTICAL_MODEL.py to generate the three files. I added to the tutorial the missing step: https://github.com/mccoy-lab/LD-PGTA/wiki/LD-PGTA-tutorial#models
