### ISSUE TITLE
subsample num is not constant

### ISSUE THREAD

**Issue by lituan** [mccoy-lab/LD-PGTA#3]
Hi

I found that,  in ANEUPLOIDY_TEST.py  subsamples parameter is set as 32, but not all window has 32 subsamples, some has 15 subsamples,  in mean_and_std_of_mean_of_rnd_var function, subsample num is an important parameter, is this intended or something else ?

**Comment by scikal** [comment]
Given a genomic window with X reads that overlap known SNPs and Y reads that are sampled in each bootstrap iteration, the number of unique subsamples is merely the binomial coefficient X!/(Y! * (X-Y)!). The algorithm adjusts the number of subsamples according to the theoretical limit. Thus, if you set the subsamples parameter to 1,024 and the there are only 512 unique subsamples in a genomic window, then it would adjust the parameter to 512 for this specific genomic window. This just increases the efficiency of the algorithm by avoiding unnecessary/unmeaningful subsamples.
